# Generated by Django 4.2.4 on 2023-11-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_authormanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorManager',
        ),
    ]
