from project.controller import Controller
from project.decoration.plant import Plant
main_control = Controller()
print(main_control.add_aquarium("FreshwaterAquarium", "beautiful one"))
print(main_control.add_aquarium("salty", "fresh one"))
print(main_control.add_aquarium("FreshwaterAquarium", "new one"))
print(main_control.add_aquarium("SaltwaterAquarium", "one"))
print(main_control.add_aquarium("SaltwaterAquarium", "two"))
print(main_control.add_decoration("house"))
print(main_control.add_decoration("rocks"))
print(main_control.add_decoration("Ornament"))
print(main_control.add_decoration("Plant"))
print(main_control.add_decoration("Plant"))
print(main_control.add_decoration("Plant"))
print(main_control.insert_decoration("fresh", "house"))
print(main_control.insert_decoration("beautiful one", "Plant"))
print(main_control.add_fish("beautiful one", "FreshwaterFish", "Nemo", "clown", 40))
print(main_control.feed_fish("beautiful one"))
print(main_control.calculate_value("beautiful one"))
print(main_control.report())
