# Generated by Django 4.2.4 on 2023-10-30 09:36

from django.db import migrations


def set_age_group(apps, schema_editor):
    person = apps.get_model("main_app", "Person")
    for p in person.objects.all():
        if p.age <= 12:
            p.age_group = "Child"
        elif p.age <= 13 and p.age <= 17:
            p.age_group = "Teen"
        elif p.age >= 18:
            p.age_group = "Adult"
        else:
            p.age_group = "No age group"
        p.save()


def reverse_age_group(apps, schema_editor):
    person = apps.get_model("main_app", "Person")
    for p in person.objects.all():
        p.age_group = "No age group"
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=reverse_age_group)
    ]
