# Generated by Django 4.2.4 on 2023-10-30 10:05

from django.db import migrations

def set_rarity(apps, schema_editor):
    item = apps.get_model("main_app", "Item")
    for p in item.objects.all():
        if p.price <= 10:
            p.rarity = "Rare"
        elif 11 <= p.price <= 20:
            p.rarity = "Very Rare"
        elif 21 <= p.price <= 30:
            p.rarity = "Extremely Rare"
        elif p.price >= 31:
            p.rarity = "Mega Rare"
        else:
            p.rarity = "empty"
        p.save()


def reverse_rarity(apps, schema_editor):
    item = apps.get_model("main_app", "Item")
    for p in item.objects.all():
        p.rarity = "empty"
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity, reverse_code=reverse_rarity)
    ]
